# Generated by Django 3.1.3 on 2023-09-02 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('card_site1', models.CharField(blank=True, max_length=512, null=True, verbose_name='卡密网站1')),
                ('card_site2', models.CharField(blank=True, max_length=512, null=True, verbose_name='卡密网站2')),
                ('card_site3', models.CharField(blank=True, max_length=512, null=True, verbose_name='卡密网站3')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['-update_time'],
            },
        ),
    ]
