# Generated by Django 3.1.3 on 2023-09-02 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SearchKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('keyword', models.CharField(max_length=64, verbose_name='搜索关键词')),
                ('search_num', models.IntegerField(default=1, verbose_name='搜索次数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'ordering': ['-search_num'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('word', models.CharField(max_length=64, unique=True, verbose_name='分词')),
                ('frequency', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='词频')),
                ('property', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='词性')),
            ],
            options={
                'verbose_name': '结巴分词库',
                'verbose_name_plural': '结巴分词库',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('slug', models.CharField(default='', max_length=60, verbose_name='slug标题')),
                ('summary', models.TextField(default='', verbose_name='摘要')),
                ('cover_urls', models.CharField(max_length=1000, verbose_name='封面图urls')),
                ('body', models.TextField(verbose_name='正文')),
                ('download_link', models.CharField(max_length=500, verbose_name='下载链接')),
                ('dl_is_valid', models.BooleanField(default=True, verbose_name='链接是否有效')),
                ('extract_code', models.CharField(max_length=500, verbose_name='提取码')),
                ('baidu_share_content', models.TextField(verbose_name='百度分享')),
                ('upack_code', models.CharField(blank=True, default='laowang', max_length=500, null=True, verbose_name='解压码')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('download_num', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('price', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100), (150, 150), (200, 200)], default=1, verbose_name='价格')),
                ('author_id', models.IntegerField(default=1, verbose_name='作者')),
                ('category', models.CharField(choices=[('all', '全部')], default='all', max_length=100, verbose_name='分类')),
                ('no_watermark', models.BooleanField(default=False, verbose_name='无水印')),
                ('has_face', models.BooleanField(default=False, verbose_name='露脸')),
                ('is_collection', models.BooleanField(default=False, verbose_name='合集')),
                ('is_freeshare', models.BooleanField(default=False, verbose_name='freeshare首发')),
                ('tags', models.ManyToManyField(to='tag.Tags')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-update_time'],
            },
        ),
    ]
